cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string. You can use env vars too, for example:
  #   $DATABASE_URL
  #   ${DATABASE_URL:-postgresql://postgres@localhost/db}
  connection_string: ${DATABASE_URL}

  # # Same as PGSSLCERT for psql
  # ssl_cert: './postgresql.crt'
  # # Same as PGSSLKEY for psql
  # ssl_key: './postgresql.key'
  # # Same as PGSSLROOTCERT for psql
  # ssl_root_cert: './root.crt'

  # #  If a spatial table has SRID 0, then this SRID will be used as a fallback
  # default_srid: 4326

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  # auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  # auto_publish: false

  # Associative arrays of table sources
  tables:

    # --- Standard --- #

    standard_railway_line_med:
      schema: public
      table: standard_railway_line_med
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: string
        tunnel: boolean
        bridge: boolean

    standard_railway_turntables:
      schema: public
      table: standard_railway_turntables
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        railway: string

    standard_railway_line_fill:
      schema: public
      table: standard_railway_line_fill
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: string
        tunnel: boolean
        bridge: boolean

    standard_railway_text_stations:
      schema: public
      table: standard_railway_text_stations
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        station: string
        label: string

    standard_railway_symbols:
      schema: public
      table: standard_railway_symbols
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        man_made: string

    standard_railway_text:
      schema: public
      table: standard_railway_text
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        ref: string
        track_ref: string
        label: string

    standard_railway_text_km:
      schema: public
      table: standard_railway_text_km
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        pos: string
        zero: boolean

    standard_railway_switch_ref:
      schema: public
      table: standard_railway_switch_ref
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        ref: string
        railway_local_operated: string

    # --- Signals --- #

    signals_railway_line:
      schema: public
      table: signals_railway_line
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        layer: number
        rank: number
        train_protection: string

    signals_railway_signals:
      schema: public
      table: signals_railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        ref: string
        feature: string
        deactivated: boolean

    signals_signal_boxes:
      schema: public
      table: signals_signal_boxes
      srid: 3857
      geometry_column: way
      geometry_type: GEOMETRY
      properties:
        ref: string
        name: string

fonts:
  - /config/fonts
