version: '2'
services:
  db:
    image: db:v1
    build:
      context: .
      dockerfile: db.Dockerfile
    command: |
      postgres 
      -c shared_preload_libraries='pg_stat_statements'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/postgres-data
    shm_size: 1g
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - PGDATA=/var/lib/postgresql/postgres-data

  import:
    image: import:v1
    build:
      context: .
      dockerfile: import.Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/data
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE

  martin-cp:
    image: ghcr.io/maplibre/martin
    entrypoint: []
    command: [
      'sh',
      '-c',
      'martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 0 --max-zoom 6 "--bbox=$$BBOX" --source railway_line_low --output-file /tiles/railway_line_low.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 0 --max-zoom 6 "--bbox=$$BBOX" --source standard_railway_text_stations_low --output-file /tiles/standard_railway_text_stations_low.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 7 --max-zoom 7 "--bbox=$$BBOX" --source railway_line_med --output-file /tiles/railway_line_med.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 7 --max-zoom 7 "--bbox=$$BBOX" --source standard_railway_text_stations_med --output-file /tiles/standard_railway_text_stations_med.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 8 --max-zoom "$$MAX_ZOOM" "--bbox=$$BBOX" --source standard_railway_turntables,standard_railway_line_fill,standard_railway_text_stations,standard_railway_symbols,standard_railway_text_km,standard_railway_switch_ref --output-file /tiles/standard.mbtiles --on-duplicate override && 
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 8 --max-zoom "$$MAX_ZOOM" "--bbox=$$BBOX" --source speed_railway_line_casing,speed_railway_line_fill,speed_railway_signals --output-file /tiles/speed.mbtiles --on-duplicate override && 
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 8 --max-zoom "$$MAX_ZOOM" "--bbox=$$BBOX" --source signals_railway_line,signals_railway_signals,signals_signal_boxes --output-file /tiles/signals.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 8 --max-zoom "$$MAX_ZOOM" "--bbox=$$BBOX" --source electrification_railway_line,electrification_future,electrification_signals --output-file /tiles/electrification.mbtiles --on-duplicate override &&
      martin-cp --config /config/configuration.yml --mbtiles-type flat --min-zoom 8 --max-zoom "$$MAX_ZOOM" "--bbox=$$BBOX" --source gauge_railway_line_low,gauge_railway_line --output-file /tiles/gauge.mbtiles --on-duplicate override'
    ]
    volumes:
      - ./martin:/config
      - ./tiles:/tiles
    depends_on:
      - db
    environment:
      # AT: --bbox=9.52678,46.36851,17.16273,48.90201
      # DE: --bbox=5.864417,47.26543,15.05078,55.14777
      # FI: --bbox=19.02427,59.28783,31.6159,70.09959
      # NL: --bbox=2.99,50.74753,7.230455,54.01786
      - BBOX=2.99,50.74753,7.230455,54.01786
      - MIN_ZOOM=0
      - MAX_ZOOM=14
      - DATABASE_URL=postgresql://postgres@db:5432/gis

  martin:
    build:
      dockerfile: martin.Dockerfile
    depends_on:
      - db
    volumes:
      - ./martin:/config
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/gis

  martin-static:
    build:
      dockerfile: martin-static.Dockerfile

  martin-proxy:
    build:
      dockerfile: proxy.Dockerfile
    volumes:
      - ./proxy/index.html:/etc/nginx/public/index.html
    ports:
      - '8000:8000'
    environment:
      PROXY_UPSTREAM: martin:3000
      PUBLIC_PROTOCOL: http
      PUBLIC_HOST: localhost:8000
      NGINX_RESOLVER: '127.0.0.11 ipv6=off'
