app = 'openrailwaymap'
primary_region = 'ams'

[build]
  dockerfile = 'proxy.Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PROXY_UPSTREAM = "ams.openrailwaymap-tiles.internal:3000"
  PUBLIC_PROTOCOL = "https"
  PUBLIC_HOST = "openrailwaymap.fly.dev"
  NGINX_RESOLVER = "[fdaa::3] valid=10m ipv6=on"
  NGINX_CACHE_TTL = "86400"
  CLIENT_CACHE_TTL_FRESH = "8182"
  CLIENT_CACHE_TTL_STALE = "604800"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
