version: 2.1

jobs:
  import-data:
    machine:
      image: default
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            # Install Fly
            
            # Download data
            curl --progress-bar https://download.geofabrik.de/europe/andorra-latest.osm.pbf --output data/data.osm.pbf

workflows:
  commit:
    jobs:
      - update-data
  update-data:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-data
