version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium

jobs:

#  # Install Fly
#  wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
#  ./flyctl auth docker
#  docker build -t registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM .
#  docker push registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM
#  ./flyctl deploy -i registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME

  update-data:
    executor: default
    steps:
      - checkout
      - run:
          command: |
            # Download data
            curl --progress-bar https://download.geofabrik.de/europe/andorra-latest.osm.pbf --output data/data.osm.pbf
            
            docker compose build db
            docker compose up --no-build --wait db
            
            docker compose build import
            
            env \
              OSM2PGSQL_DATAFILE=data.osm.pbf \
              OSM2PGSQL_CACHE=7000 \
              OSM2PGSQL_NUMPROC=2 \
              docker compose run --no-build --rm import import
            
            #            env TILES=low-med docker compose run --build --rm martin-cp
            #            env TILES=standard docker compose run --build --rm martin-cp
            #            env TILES=speed docker compose run --build --rm martin-cp
            #            env TILES=signals docker compose run --build --rm martin-cp
            #            env TILES=electrification docker compose run --build --rm martin-cp
            #            env TILES=gauge docker compose run --build --rm martin-cp
            
            ls -las tiles/

workflows:
  commit:
    jobs:
      - update-data
  update-data:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-data
