version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium

jobs:
  update-data:
    executor: default
    steps:
      - checkout
      - run:
          command: |
            echo "Hello executor!"

workflows:
  commit:
    jobs:
      - update-data
  update-data:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-data
