version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
#      docker_layer_caching: true
    resource_class: medium

jobs:

#  # Install Fly
#  wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
#  ./flyctl auth docker
#  docker build -t registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM .
#  docker push registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM
#  ./flyctl deploy -i registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME

  update-data:
    executor: default
    steps:
      - checkout
      - run: docker compose build db
      - run: docker compose build import
      - run: docker compose build martin-cp
      - run: docker compose up --wait db
      - run: curl --progress-bar https://download.geofabrik.de/europe/andorra-latest.osm.pbf --output data/data.osm.pbf
      - run:
          environment:
            OSM2PGSQL_DATAFILE: data.osm.pbf
            OSM2PGSQL_CACHE: '7000'
            OSM2PGSQL_NUMPROC: '2'
          command: docker compose up import
      - run:
          environment:
            TILES: low-med
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: standard
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: speed
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: signals
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: electrification
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: gauge
          command: docker compose run --rm martin-cp
      - run: ls -las tiles/

workflows:
  commit:
    jobs:
      - update-data
  update-data:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-data
