version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
#      docker_layer_caching: true
    resource_class: medium

jobs:

#  # Install Fly
#  wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
#  ./flyctl auth docker
#  docker build -t registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM .
#  docker push registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM
#  ./flyctl deploy -i registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME

  generate-tiles:
    executor: default
    steps:
      - checkout
      - run: docker compose build db
      - run: docker compose build import
      - run: docker compose build martin-cp
      - run: docker compose up --wait db
      - run: curl --verbose --progress-bar https://download.geofabrik.de/europe-latest.osm.pbf --output data/data.osm.pbf
      - run:
          environment:
            OSM2PGSQL_DATAFILE: data.osm.pbf
            OSM2PGSQL_CACHE: '7000'
            OSM2PGSQL_NUMPROC: '2'
          command: docker compose up import
      - run:
          environment:
            TILES: low-med # << matrix.tiles >>
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: standard
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: speed
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: signals
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: electrification
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run:
          environment:
            TILES: gauge
            BBOX: '-11.3818,35.8891,25.0488,57.3976'
          command: docker compose run --rm martin-cp
      - run: ls -las tiles/
      - persist_to_workspace:
          root: tiles
          paths:
            - '*.mbtiles'

  deploy-proxy:
    executor: default
    steps:
      - checkout
      - run: wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
      - run: ./flyctl deploy --config proxy.fly.toml --local-only

  deploy-tiles:
    executor: default
    steps:
      - checkout
      - run: wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: tiles
      - run: ls -lah tiles/
      - run: ./flyctl deploy --config martin-static.fly.toml --local-only

workflows:
  commit:
    jobs:
      - generate-tiles: {}
#          matrix:
#            parameters:
#              tiles:
#                - low-med
#                - standard
#                - speed
#                - signals
#                - electrification
#                - gauge
      - deploy-proxy:
          context:
            - fly-proxy
      - deploy-tiles:
          requires:
            - generate-tiles
          context:
            - fly-tiles

  auto-deployment:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-tiles: {}
      - deploy-proxy: {}
      - deploy-tiles:
          requires:
            - generate-tiles
