version: 2.1
jobs:
  update-data:   
    machine:
      image: default
    resource_class: medium
    steps:
      - checkout
      - run: echo "Hello executor!"
      
workflows:
  commit:
    jobs:
      - update-data
  update-data:
    triggers:
      - schedule:
          # Run daily at 3:47 UTC
          cron: "47 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-data
