version: 2.1
jobs:
  test:   
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run: echo "Hello executor!"
      
workflows:
  example:
    jobs:
      - test
