openapi: 3.1.0

info:
  description: API to search for OpenRailwayMap-vector
  contact:
    name: Hidde Wieringa
    email: openrailwaymap@hiddewieringa.nl
    url: https://github.com/hiddewie/OpenRailwayMap-vector
  license:
    identifier: GPL-2.0-or-later
    name: GNU General Public License v2.0 or later
  title: OpenRailwayMap API
  version: current

servers:
  - url: https://openrailwaymap.fly.dev

paths:
  /api/status:
    get:
      description: Status endpoint
      summary: Status endpoint

  /api/facility:
    get:
      summary: Facility search
      description: |
        The facility endpoint returns detail of a facility (station, junction, yard, …) by its name, UIC reference or reference.
              
        The parameters q, name, ref and uic_ref are mutually exclusive.
        
        It takes the first keyword of (name,uicref,ref) and the optional the operator to search for the data.

      parameters:
        - name: q
          in: query
          schema:
            type: string
          description: |
            search term (will be looked up in all `name=*` tags, `railway:ref=*` and `uic_ref=*`)
        - name: name
          in: query
          schema:
            type: string
          description: |
            search term (name search only)
        - name: ref
          in: query
          schema:
            type: string
          description: |
            search by official facility reference number/code only
        - name: uic_ref
          in: query
          schema:
            type: string
          description: |
            search by UIC reference number of a station (uses OSM tag `uic_ref=*`)
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 200
          description: maximum number of results

  /api/milestone:
    get:
      summary: Milestone search
      description: |
        The milestone endpoint returns the position of milestones or other items such as signals or level crossings with a mapped position on a line.
        
        The API will return the features within a maximum distance of 10 km (hardcoded). The presence of an `operator=*` tag on the tracks is honoured, it will be used to
        distinguish reference numbers used by different infrastructure operators and/or in different countries.
        
        Mileage is read from the OSM tags `railway:position=*` and `railway:position:exact=*` with precedence of the exact mileage. The tracks must be tagged with a reference number (OSM tag `ref=*`).
        
        The tracks must not tagged with `service=*` (this condition does not apply to tracks with `usage=industrial/military/test`).
        
        Negative mileage is supported but gaps in mileage or duplicated positions (if railway lines are reroute) are not supported. For example, you cannot query for `16.8+200` or things like that.
